version: "3.8"

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-config/el_tiempo.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql    # volumen para persistencia
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: el_tiempo
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - backend

  apache:
    build:
      context: .
      dockerfile: Apache.Dockerfile
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./proyecto-tiempo:/var/www/html
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      DB_HOST: mariadb
      DB_USERNAME: admin
      DB_PASSWORD: admin
      DB_DATABASE: 
    depends_on:
      - db1
    restart: always
    networks:
      - backend
      - frontend

volumes:
  mariadb_data:

networks:
  backend:
  frontend:
